// Code generated by SQLBoiler 4.18.0 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Credentials string
	Sessions    string
	Users       string
}{
	Credentials: "credentials",
	Sessions:    "sessions",
	Users:       "users",
}
